# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-06 11:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('phone', models.IntegerField(unique=True)),
                ('max_borrowing', models.IntegerField(default=5)),
                ('balance', models.FloatField(default=0.0)),
                ('photo', models.ImageField(blank=True, upload_to='images/')),
                ('status', models.IntegerField(choices=[(0, 'normal'), (-1, 'overdue')], default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
